// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMWEHq4z7omugkiwu7N1X0T1chtUXs5NU',
    appId: '1:61439914019:web:24f50c295ade0cd2eec196',
    messagingSenderId: '61439914019',
    projectId: 'movie-app-e0407',
    authDomain: 'movie-app-e0407.firebaseapp.com',
    storageBucket: 'movie-app-e0407.firebasestorage.app',
    measurementId: 'G-S4VJRS4DY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvTYUcB9yakoJdX4MeFjGpIRjHLZPdbCs',
    appId: '1:61439914019:android:f04b4e51ca86174aeec196',
    messagingSenderId: '61439914019',
    projectId: 'movie-app-e0407',
    storageBucket: 'movie-app-e0407.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAunbgCOS8a10VpAHSjdR-mhftsRvONjmE',
    appId: '1:61439914019:ios:ff8a7e1750ac4719eec196',
    messagingSenderId: '61439914019',
    projectId: 'movie-app-e0407',
    storageBucket: 'movie-app-e0407.firebasestorage.app',
    iosBundleId: 'y',
  );
}
